name: Send Mail
on: push

jobs:
  mail:
    runs-on: ubuntu-latest

    steps:
    - name: Sending a mail
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        secure: true
        username: ${{ secrets.MAIL_ADDRESS }}
        password: ${{ secrets.MAIL_PASSWORD }}
        from: "Meganraj <${{ secrets.MAIL_ADDRESS }}>"
        to: "mrcreations773@gmail.com"
        subject: "GitHub Actions Email Test"
        body: "Hi, this is Meganraj testing GitHub Actions email."
